### ISSUE TITLE
Implement Batch size restrictions 

### ISSUE THREAD

**Issue by brechtmann** [kipoi/models#209]
To solve the Basenji Issue in the long run we could think of implementing a batch size restriction.

This could be an option in the model.yaml file, which is then handed over to the respective data-loader. It could also be specified in the default data loader section:

```
default_dataloader: 
  defined_as: kipoiseq.dataloaders.SeqIntervalDl
  default_args:
    auto_resize_len: 131072
    ignore_targets: True  # don't return any output labels using the bed file
```
